### ISSUE TITLE
genoverse leaves some dangling deferreds after browser.destroy()

### ISSUE THREAD

**Issue by BurkovBA** [DECIPHER-genomics/Genoverse#53]
I'm observing the following incorrect behaviour with Genoverse.

I initialise Genoverse with 3 tracks, one of them is loading very slowly.

![screen shot 2018-05-10 at 18 00 14](https://user-images.githubusercontent.com/7602655/39882594-23dc5e14-547c-11e8-8529-9a3aea2f7a31.png)

After that user might opt to destroy the browser (I call `browser.destroy()`).

If I destroy Genoverse before all the track data were loaded and their respective images were rendered by `makeImage()`/`makeFirstImage()`, 5 seconds after destruction of the browser, the asynchronous callback of `getData()` fires.

This is happening because of the following async call stack:

[loadGenome()](https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Genoverse.js#L56) -> 
[$when(Genoverse.ready, this.loadGenome(), this.loadPlugins())](https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Genoverse.js#L50) ->
[init()](https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Genoverse.js#L164) ->
[setRange()](https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Genoverse.js#L208) ->
[setScale()](https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Genoverse.js#L835) ->
[onTracks("makeFirstImage")](https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Genoverse.js#L859) -> 
[makeFirstImage()](https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Track/Controller.js#L472) ->
[makeImages()](https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Track/Controller.js#L508) ->
[makeImage()](https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Track/Controller.js#L423) ->
[getData()](https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Track/Controller.js#L450)

`getData()` creates a deferred, which fires 5 seconds after destruction of the browser. But all deferreds on tracks are supposed to be cleared by `browser.destroy()`! And indeed the list of deferreds on all tracks is empty after I call browser.destroy():

```
console.log(ctrl.browser.tracks.reduce((accumulator, track) => return accumulator.concat(track.controller.deferreds), []));
browser.destroy();
console.log(ctrl.browser.tracks.reduce((accumulator, track) => return accumulator.concat(track.controller.deferreds), []));
```

returns

```
(12) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
[]
```

I've been scratching my head for 3 days, I guess, I need help.

You can observe this behaviour here, if you try to switch species (I destroy the old instance of browser and create a new one upon species switch): https://test.rnacentral.org/genome-browser.

**Comment by simonbrent** [comment]
It's basically impossible to debug by just looking at your minified javascript, but given that call stack I would suggest adding the following:

* In `Genoverse.constructor`, add `this.deferreds = []` below the declaration of `this.events`
* In `Genoverse.loadGenomes` and `Genoverse.loadPlugins`, push the returned values to `this.deferreds` before returning.
* In `Genoverse.destroy`, abort the contents of `this.deferreds` before doing anything else.

I haven't tested this at all, so let me know if it works!

**Comment by BurkovBA** [comment]
@simonbrent Hi, Simon.

I did as you said, but as expected, this didsn't work. By the time I destroy the browser, `Genoverse.loadGenomes()` and `Genoverse.loadPlugins()` have already fired and triggered `init()` and `setRange()`, which created deferreds on tracks, and those deferreds fire later and are not cancelled.

I'm trying to create a minimal isolated test example for you on a separate OpenStack machine. If I have time to do this, I'll contact you later on and provide a link to it, so that you don't have to setup anything. But it's also likely that I won't be able to do this as I'll be away in a few days.
